version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=telegrambot
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_MAX_CONNECTIONS=100
      # Add the following lines to create a user named "quotes_user"
      - MYSQL_USER=Lift_kz
      - MYSQL_PASSWORD=Lift@2023
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./migration/dumb:/docker-entrypoint-initdb.d/
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  api:
    container_name: telegrambot-api
    build:
      context: ./
      target: production
    image: telegrambot-api
    # ensures that the db service is started before the api service. 
    depends_on:
            db:
                condition: service_healthy
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: Lift_kz
      DB_PASSWORD: Lift@2023
      DB_NAME: telegrambot
      # This is useful when you want to mount the source code or project files from the host machine into the containe
    volumes:
      - ./:/src

volumes:
  mysql-volume: