version: "3.9"

networks:
  internal:
    driver: bridge


services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=cert_db
      - POSTGRES_USER=cert
      - POSTGRES_PASSWORD=qwerty
    networks:
      - internal
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cert -d cert_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080   
         

  cache:
    image: redis:6.2-alpine
    restart: always
    networks:
      - internal
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=cache
    networks:
      - internal
    depends_on:
      - postgres
      - cache